version: '3.8'

services:
  jmcloudpro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jmcloudpro
    ports:
      - "80:80"
    restart: always
    environment:
      - NGINX_PORT=80
    volumes:
      - ./images:/usr/share/nginx/html/images
      - ./logs:/var/log/nginx

networks:
  default:
    name: jmcloudpro_network
    driver: bridge
